<?php

namespace   app;
use wfm\interfaces\I3D;
use wfm\Product;

class  BookProduct extends Product implements I3D
{
    public $numPages;
    public $action1;
    public $action2;

    public function __construct($name,$price,$numPages)
    {
        parent::__construct($name,$price);
        $this->numPages=$numPages;
        $this->setDiscount(5 );
//        var_dump(self::class);




    }

    public function __toString(): string
    {
        // TODO: Implement __toString() method.

        return $this->getProduct();
    }
    public function __get(string $name)
    {
        // TODO: Implement __get() method.
          $name=ucfirst($name);

        $method="get{$name}";
        if (method_exists($this,$method))
        {
            return $this->method();
        }
//        var_dump($method);
    }
    public function __set(string $name, $value): void
    {
        // TODO: Implement __set() method.
        var_dump($name,$value);
    }

    public function test()
    {
        // TODO: Implement test() method.
      var_dump(self::class);
    }

    public function getProduct()
    {
        $out= parent::getProduct(); // TODO: Change the autogenerated stub
        $out.="Price no skidiki {$this->price}<br>";
        $out.="Count link {$this->numPages}<br>";
        $out.="Skidki {$this->getDiscount()}<br>";
        return $out;
    }

    public function getnumPages()
    {
        return $this->numPages;
        // TODO: Change the autogenerated stub
    }
    public function addProduction($name, $price,$numPages=0)
    {
        // TODO: Implement addProduction() method.
        var_dump($name);
        var_dump($price);
        var_dump($numPages);
    }
    public function doAction1()
    {
      echo   $this->action1='<p>Success2 </p>';
        return $this;
    }
    public function doAction2()
    {
        echo  $this->action2='<p>Success3</p>';
        return $this;
    }
}