<?php

namespace   app;
use wfm\interfaces\I3D;
use wfm\Product;

class  BookProduct extends Product implements I3D
{
    public $numPages;
    const TEST=20;

    public function __construct($name,$price,$numPages)
    {
        parent::__construct($name,$price);
        $this->numPages=$numPages;
        $this->setDiscount(5 );
//        var_dump(self::class);




    }
    public function test()
    {
        // TODO: Implement test() method.
       //  var_dump(self::class);
    }

    public function getProduct()
    {
        $out= parent::getProduct(); // TODO: Change the autogenerated stub
        $out.="Price no skidiki {$this->price}<br>";
        $out.="Count link {$this->numPages}<br>";
        $out.="Skidki {$this->getDiscount()}<br>";
        return $out;
    }

    public function getnumPages()
    {
        return $this->numPages;
        // TODO: Change the autogenerated stub
    }
    public function addProduction($name, $price,$numPages=0)
    {
        // TODO: Implement addProduction() method.
        var_dump($name);
        var_dump($price);
        var_dump($numPages);
    }
}