<?php
class  Book extends Product
{
    public $numPages;

    public function __construct($name,$price,$numPages)
    {
        $this->numPages=$numPages;
        parent::__construct($name,$price);


    }
    public function getProduct()
    {
        $out= parent::getProduct(); // TODO: Change the autogenerated stub
        $out.="Cpu {$this->numPages}<br>";
    }

    public function getCpu()
    {
        return $this->numPages;
        // TODO: Change the autogenerated stub
    }
}