<?php
 class  NoteBookProduct extends Product
 {
      public $cpu;

      public function __construct($name,$price,$cpu)
      {
            $this->cpu=$cpu;
           parent::__construct($name,$price);


      }
       public function getProduct()
       {
           $out= parent::getProduct(); // TODO: Change the autogenerated stub
           $out.="Cpu {$this->cpu}<br>";
       }

     public function getCpu()
      {
          return $this->cpu;
          // TODO: Change the autogenerated stub
      }
 }